spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/frotapm
    username: postgres
    password: lucas3213
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${JWT_SECRET}

