spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/frotapm
    username: frotapm
    password: 123456
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      encoding: UTF-8
  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: ${JWT_SECRET}

