spring:
  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres
    username: postgres.hghlaayxdzhoudydqmuf
    password: pmto8bpm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # ou "none", "validate", "create", etc.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
