#spring:
#  datasource:
#    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres
#    username: postgres.hghlaayxdzhoudydqmuf
#    password: pmto8bpm
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update # ou "none", "validate", "create", etc.
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
spring:
  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres
    username: postgres.fjtsgyqbwhjynaawvwpc
    password: lucas3213
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5          # 🔧 Limita para até 5 conexões simultâneas
      minimum-idle: 2               # Conexões mínimas ociosas mantidas no pool
      idle-timeout: 10000           # Tempo em ms para matar conexões ociosas (10s)
      max-lifetime: 1800000         # Tempo de vida máximo da conexão (30min)
      connection-timeout: 30000     # Timeout de conexão (30s)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
